apiVersion: v2
name: paladin-operator
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.0.0"

dependencies:
  - name: paladin-operator-crd
    version: 0.0.0
    repository: "file://../paladin-operator-crd/"
    condition: installCRDs

# install cert-manager dependencies if cert-manager is enabled
  - name: cert-manager-namespace
    version: 0.0.0
    repository: "file://../cert-manager-namespace/"
    condition: cert-manager.enabled
  - name: cert-manager
    version: v1.16.1
    repository: https://charts.jetstack.io
    condition: cert-manager.enabled

# install prometheus dependencies if prometheus is enabled
  - name: prometheus-namespace
    version: 0.0.0
    repository: "file://../prometheus-namespace/"
    condition: prometheus.enabled
  - name: prometheus
    version: "15.8.0"  # Update this to the version you prefer
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: prometheus.enabled

