apiVersion: core.paladin.io/v1alpha1
kind: BesuGenesis
metadata:
  labels:
    app.kubernetes.io/name: operator-go
    app.kubernetes.io/managed-by: kustomize
  name: testnet
spec:
  chainID: 1337
  gasLimit: 700000000
  consensus: qbft
  blockPeriod: 100ms
  emptyBlockPeriod: 10s
  initialValidators:
  - node1

