name: Build core and operator images
on:
  push:
    branches:
      - wf-build-image
    paths:
    # run only on changes of code files
      - '**.go'
      - '**.java'
      - '**/build.gradle'
      - '**/Dockerfile'
      - '.github/workflows/build-image*.yaml' 
jobs:
    core:
        uses: ./.github/workflows/build-image-job.yaml
        with:
          dockerfile: ./Dockerfile
          registry: docker.io
          image: ${{ github.repository_owner }}/paladin
          image_tag: ${{ github.ref_name }}
          push: true
        secrets:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    operator:
        uses: ./.github/workflows/build-image-job.yaml
        with:
          dockerfile: ./operator/Dockerfile
          registry: docker.io
          image: ${{ github.repository_owner }}/paladin-operator
          image_tag: ${{ github.ref_name }}
          push: true
        secrets:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
