name: Helm Chart release

on:
  workflow_dispatch:
    inputs:
      latest:
        required: false
        type: boolean
        default: false

jobs:
  helm-chart-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      # Install protoc only on non-Windows systems
      - name: Install protoc
        run: |
          PB_REL="https://github.com/protocolbuffers/protobuf/releases"
          curl -LO $PB_REL/download/v25.1/protoc-25.1-linux-x86_64.zip
          unzip protoc-25.1-linux-x86_64.zip -d protoc
          echo "${PWD}/protoc/bin" >> $GITHUB_PATH

      # Set up Java
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      # Set up Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          check-latest: true
          cache-dependency-path: |
            **/*.sum

      # Set up Gradle
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      
      - name: Prepare CRD chart
        working-directory: operator
        run: gradle prepareCRDsChart

      - name: Prepare operator chart
        run: ./gradlew prepareOperatorChart

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          mark_as_latest: ${{ inputs.latest }}
          charts_dir: "operator/charts"
          skip_existing: true
        env: 
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
